doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '10.4'  # Assurez-vous que cela correspond à votre version MySQL
        types:
            enum: Doctrine\DBAL\Types\StringType  # Ajoutez cette ligne pour les enums si nécessaire
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false  # Changez cela en false si vous voulez spécifier manuellement les entités
        mappings:
            App:
                type: attribute  # Si vous utilisez des attributs Doctrine, sinon utilisez 'annotation'
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
