knp_paginator:
  page_range: 5 # number of pages to show in the range
  default_options:
    page_name: page # the name of the query parameter
    sort_field_name: sort # name for the sorting parameter
    sort_direction_name: direction # name for the sorting direction
    distinct: true # Ensure distinct results
