security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\User: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    google_oauth:
      pattern: ^/connect/google
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\GoogleAuthenticator
      entry_point: App\Security\GoogleAuthenticator
      # Partager la session avec le firewall main
      context: main_context

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppAuthAuthenticator
      form_login: false # Explicitly disable if not using
      logout:
        path: app_logout
        target: app_login
      entry_point: App\Security\AppAuthAuthenticator
      # Partager la session avec le firewall google_oauth
      context: main_context

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/signup, roles: PUBLIC_ACCESS }
    - { path: ^/connect/google, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }
