# config/services.yaml

parameters:
  profile_photos: "%kernel.project_dir%/public/uploads/profile_photos"
  cvs_directory: "%kernel.project_dir%/public/uploads/cvs"
  STRIPE_PUBLIC_KEY: '%env(STRIPE_PUBLIC_KEY)%'

twig:
    globals:
        STRIPE_PUBLIC_KEY: '%STRIPE_PUBLIC_KEY%'

 

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # ----- Ajoute cette section -----
 # App\Service\StripeService:
  #  arguments:
   #   $secretKey: '%env(STRIPE_SECRET_KEY)%'
  # ---------------------------------

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
