# services.yaml

# Define the parameters outside the `services` section
parameters:
  gemini_api_url: "%env(GEMINI_API_URL)%"
  gemini_api_key: "%env(GEMINI_API_KEY)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: "../src/"
    exclude: "../src/{DependencyInjection,Entity,Tests,Kernel.php}"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  App\Controller\EmployeeController:
    autowire: true
    autoconfigure: true
    public: true

  App\Repository\CongeRepository:
    autowire: true
    autoconfigure: true
    public: false

  # Configure GeminiService to inject the parameters
  App\Service\GeminiService:
    arguments:
      $apiUrl: "%gemini_api_url%"
      $apiKey: "%gemini_api_key%"
